#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM laradock/php-fpm:2.0-71

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>


COPY ./sources.list.stretch /etc/apt/sources.list

RUN apt-get update \
    && apt-get -y install supervisor


################################
#Rabbmitmq

###############################

RUN apt-get update\
    && apt-get -y install librabbitmq-dev\
    && pecl  install amqp 1.9.3\
    && docker-php-ext-enable amqp

#################################
RUN  printf "\n" | pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis 


#####################################
# Swoole EXTENSION FOR PHP 7
#####################################

RUN  pecl install swoole \
    &&  docker-php-ext-enable swoole 

#####################################
# Opcache:
#####################################

RUN  docker-php-ext-install opcache 

# Copy opcache configration
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini



ADD ./laravel.ini /usr/local/etc/php/conf.d

RUN mkdir -p /var/www

#
#--------------------------------------------------------------------------
# Optional Supervisord Configuration
#--------------------------------------------------------------------------
#
# Modify the ./supervisor.conf file to match your App's requirements.
# Make sure you rebuild your container with every change.
#

COPY supervisord.conf /etc/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

#
#--------------------------------------------------------------------------
# Optional Software's Installation
#--------------------------------------------------------------------------
#
# If you need to modify this image, feel free to do it right here.
#
    # -- Your awesome modifications go here -- #


#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#
WORKDIR /var/www



