#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# To edit the 'php-fpm' base Image, visit its repository on Github
#    https://github.com/Laradock/php-fpm
#
# To change its version, see the available Tags on the Docker Hub:
#    https://hub.docker.com/r/laradock/php-fpm/tags/
#
# Note: Base Image name format {image-tag}-{php-version}
#

FROM registry.cn-beijing.aliyuncs.com/lnmprrsw/php-base:v1.0

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

COPY ./sources.list.stretch /etc/apt/sources.list


################################
#Rabbmitmq

###############################

RUN apt-get update\
    && apt-get -y install librabbitmq-dev\
    && pecl  install amqp 1.9.3\
    && docker-php-ext-enable amqp

#####################################
# PHP REDIS EXTENSION FOR PHP 7.0
#####################################

RUN printf "\n" | pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis 

#####################################
# Swoole EXTENSION FOR PHP 7
#####################################

RUN pecl install swoole \
    &&  docker-php-ext-enable swoole 


#####################################
# Opcache:
#####################################

RUN  docker-php-ext-install opcache 

# Copy opcache configration
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini


ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

#RUN rm -r /var/lib/apt/lists/*

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
