version: '2'

services:
### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www

### PHP-FPM Container #######################################

    php-fpm:
      image: registry.cn-beijing.aliyuncs.com/lnmprrsw/php-fpm:latest
      volumes_from:
        - applications
      restart: always
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      networks:
        - backend

    php-worker:
      image: registry.cn-beijing.aliyuncs.com/lnmprrsw/php-worker:latest
      ports:
        - "5200:5200"
      restart: always
      volumes_from:
          - applications
      volumes:
        - ./php-worker/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ./php-worker/conf.d:/etc/supervisor/conf.d
        - ./php-worker/log:/etc/supervisor/log
      networks:
        - backend

### NGINX Server Container ##################################

    nginx:
      image: registry.cn-beijing.aliyuncs.com/lnmprrsw/nginx:latest
      volumes_from:
        - applications
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend


### MySQL Container #########################################

    mysql:
      image: registry.cn-beijing.aliyuncs.com/lnmprrsw/mysql:latest
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ="Asia/Shanghai"
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend


### Redis Container #########################################

    redis:
      image: registry.cn-beijing.aliyuncs.com/lnmprrsw/redis:latest
      volumes:
        - ./redis/${REDIS_VERSION}:/etc/redis:ro
        - ${DATA_SAVE_PATH}/redis/data:/data
      privileged: true
      ports:
        - "${REDIS_PORT}:6379"
      command:
        - redis-server
        - /etc/redis/redis.conf
      networks:
        - backend


### RabbitMQ Container ######################################

    rabbitmq:
      image: registry.cn-beijing.aliyuncs.com/lnmprrsw/rabbitmq:latest
      ports:
        - "${RABBITMQ_NODE_HOST_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
      privileged: true
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      depends_on:
        - php-fpm
      networks:
        - backend


### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
 
